# Generated by Django 6.1 on 2026-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('chat', 'Chat'), ('api', 'API'), ('system', 'System'), ('resource', 'Resource'), ('agent', 'Agent')], db_index=True, default='api', max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenant_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='tenant_logs_tenant__3ac1e0_idx'), models.Index(fields=['tenant_id', 'level'], name='tenant_logs_tenant__a687bf_idx'), models.Index(fields=['tenant_id', 'category'], name='tenant_logs_tenant__612769_idx'), models.Index(fields=['tenant_id', 'action'], name='tenant_logs_tenant__3cbad9_idx')],
            },
        ),
    ]
