import ForbiddenPage from '@/components/common/ForbiddenPage';
import {
  EVERYONE,
  STAFF,
  STUDENT_ONLY,
  TENANT_ADMIN_ONLY,
} from '@/lib/access';
import {
  DashboardPage,
  ChatPage,
  ResourcesPage,
  UploadResourcePage,
  QuizzesPage,
  QuizTakePage,
  CoursesPage,
  CourseDetailPage,
  MyCoursesPage,
  MyProgrammePage,
  AssignedCoursesPage,
  NotesPage,
  CalendarPage,
  BookmarksPage,
  ProgressPage,
  PlansPage,
  PlanDetailPage,
  ProfilePage,
  AdminAuditPage,
  AdminUsersPage,
  AdminQuizzesPage,
  AdminTemplatesPage,
  AdminDashboardPage,
  TenantLogsPage,
  TenantStructurePage,
  FacultyDetailPage,
  DepartmentDetailPage,
  CourseManagePage,
  AdminCoursesPage,
} from './pages';

export const tenantRoutes = [
  { path: '/dashboard', Page: DashboardPage, roles: EVERYONE },
  { path: '/courses', Page: CoursesPage, roles: EVERYONE },
  { path: '/courses/:id', Page: CourseDetailPage, roles: EVERYONE },
  { path: '/my-courses', Page: MyCoursesPage, roles: STUDENT_ONLY },
  { path: '/my-programme', Page: MyProgrammePage, roles: STUDENT_ONLY },
  { path: '/assigned-courses', Page: AssignedCoursesPage, roles: STAFF },
  { path: '/resources', Page: ResourcesPage, roles: EVERYONE },
  { path: '/resources/upload', Page: UploadResourcePage, roles: EVERYONE },
  { path: '/chat', Page: ChatPage, roles: EVERYONE },
  { path: '/quizzes', Page: QuizzesPage, roles: EVERYONE },
  { path: '/quizzes/:id/take', Page: QuizTakePage, roles: EVERYONE },
  { path: '/admin/quizzes', Page: AdminQuizzesPage, roles: STAFF },
  { path: '/admin/dashboard', Page: AdminDashboardPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/users', Page: AdminUsersPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/audit', Page: AdminAuditPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/tenant', Page: TenantStructurePage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/faculties/:id', Page: FacultyDetailPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/departments/:id', Page: DepartmentDetailPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/courses', Page: AdminCoursesPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/courses/:id', Page: CourseManagePage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/logs', Page: TenantLogsPage, roles: TENANT_ADMIN_ONLY },
  { path: '/admin/templates', Page: AdminTemplatesPage, roles: TENANT_ADMIN_ONLY },
  { path: '/notes', Page: NotesPage, roles: EVERYONE },
  { path: '/bookmarks', Page: BookmarksPage, roles: EVERYONE },
  { path: '/progress', Page: ProgressPage, roles: EVERYONE },
  { path: '/plans', Page: PlansPage, roles: EVERYONE },
  { path: '/plans/:id', Page: PlanDetailPage, roles: EVERYONE },
  { path: '/settings', Page: ProfilePage, roles: EVERYONE },
  { path: '/calendar', Page: CalendarPage, roles: EVERYONE },
  { path: '/calendar/new', Page: CalendarPage, roles: EVERYONE },
  // Redirect: legacy alias for the settings page.
  { path: '/profile', redirect: '/settings' },
  // Explicit 403 page, mounted under the same tenant guard.
  { path: '/forbidden', Page: ForbiddenPage },
];