"""
Enable PostgreSQL Row-Level Security on every tenant-scoped table.

This is the enforcement boundary behind AcademiAI's multi-tenant isolation.
Previously RLS had to be applied manually (`manage.py apply_rls` or sourcing
`sql/rls_policies.sql`); if that step was forgotten the database had NO
row-level security and cross-tenant access was prevented only by application
code.

Running RLS inside a migration guarantees that `migrate` always applies the
policies on every environment, in the correct order. See `dependencies`:
every tenant-scoped table must exist before we can alter it.

The DDL is generated by apps.common.rls (shared with the apply_rls command),
not loaded from the .sql file, because Django runs migrations through
psycopg's client-side binding which rejects the `%I` placeholders used by the
DO-block form in sql/rls_policies.sql.
"""
from django.db import migrations

from apps.common import rls


def apply_rls(apps, schema_editor):
    for stmt in rls.all_policy_statements(teardown=False):
        schema_editor.execute(stmt)


def reverse_rls(apps, schema_editor):
    for stmt in rls.all_policy_statements(teardown=True):
        schema_editor.execute(stmt)


class Migration(migrations.Migration):
    # Run AFTER every app that owns a tenant-scoped table has created its
    # tables, so the ALTER TABLE ... ENABLE/FORCE ROW LEVEL SECURITY calls
    # find them.
    dependencies = [
        ("tenants", "0003_tenantrequest"),
        ("accounts", "0002_user_avatar_key_user_avatar_preset_user_gender_and_more"),
        ("academics", "0003_semester_is_current"),
        ("resources", "0003_resourcesummary"),
        ("knowledge", "0001_initial"),
        ("chat", "0002_chatmessage_content_type"),
        ("assessments", "0001_initial"),
        ("learning", "0001_initial"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(apply_rls, reverse_rls),
    ]
