# Generated by Django 6.1 on 2026-09-06 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentsession_recent_messages'),
        ('tenants', '0003_tenantrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='agent_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('archived', 'Archived')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='title',
            field=models.CharField(blank=True, default='New conversation', max_length=140),
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('default_agent', models.CharField(blank=True, default='', max_length=40)),
                ('tone', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('coach', 'Coach')], default='balanced', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict, help_text="AI filters toggles, e.g. {'ableism': True, 'reading_order': True, 'itim': False}.")),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_settings',
            },
        ),
    ]
