# Generated by Django 6.1 on 2026-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentsession_agent_key_agentsession_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='avatar',
            field=models.CharField(blank=True, default='', help_text='Optional custom avatar URL (uploaded image or curated SVG path).', max_length=300),
        ),
    ]
