# Generated by Django 6.1 on 2026-09-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_agentsession_tenant_alter_agentsettings_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agenttoolexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
