# Generated by Django 6.1 on 2026-08-28 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_add_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribe_info', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement subscription',
                'verbose_name_plural': 'Announcement subscriptions',
                'db_table': 'platform_announcement_subscriptions',
            },
        ),
    ]
