# Generated by Django 6.1 on 2026-09-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_conceptinteraction_plan_planmilestone_plantask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcereadingposition',
            options={'ordering': ['-last_read_at']},
        ),
    ]
