# Generated by Django 6.1 on 2026-09-05 14:12

from django.db import migrations, models


def backfill_public(apps, schema_editor):
    # Before this feature, only tenant admins could create templates and every
    # template was institution-wide. Preserve that: mark existing rows public.
    PlanTemplate = apps.get_model("learning", "PlanTemplate")
    PlanTemplate.objects.update(is_public=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_resourcereadingposition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantemplate',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public templates are visible to the whole institution; private templates are visible only to their creator.'),
        ),
        migrations.RunPython(backfill_public, noop),
    ]
