# Generated by Django 6.1 on 2026-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_protect_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
