# Generated by Django 6.1 on 2026-09-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_bookmark_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressrecord',
            options={'ordering': ['-last_seen_at']},
        ),
    ]
