-- AcademiAI PostgreSQL RLS — all tenant-scoped tables
--
-- Binds every row to the current tenant via current_setting('app.current_tenant_id').
-- The setting is placed at SESSION scope by the middleware (is_local=false) so
-- that StreamingHttpResponse generators — which execute AFTER the request
-- transaction has closed — still see the tenant context. Individual helpers
-- (apps.common.db.tenant_scope) open their own atomic blocks and re-set the
-- GUC as a belt-and-braces measure for Celery tasks and streaming generators.
--
-- Policies:
--   USING      → rows visible to SELECT/UPDATE/DELETE must match the tenant
--   WITH CHECK → new rows written by INSERT/UPDATE must match the tenant
-- Without WITH CHECK, INSERTs would be silently rejected because there is
-- no policy permitting them.
--
-- This file is a human-readable SPEC of the RLS policies. The authoritative
-- DDL is generated by apps/common/rls.py and applied automatically at deploy
-- time by apps/common/migrations/0001_rls_tenant_isolation.py (which runs
-- after the tenant-scoped tables exist), and manually via the `apply_rls`
-- management command. The table list is DERIVED from the model registry in
-- rls.py — no list is maintained here, so it can never drift. The snippet
-- below mirrors rls.py by discovering tenant-scoped tables from
-- information_schema instead of a hardcoded array.

DO $$
DECLARE
  t text;
BEGIN
  FOR t IN
    SELECT table_name FROM information_schema.columns
    WHERE column_name = 'tenant_id' AND table_schema = 'public'
  LOOP
    EXECUTE format('ALTER TABLE IF EXISTS %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE IF EXISTS %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I '
      '   FOR ALL '
      '   USING (tenant_id::text = current_setting(''app.current_tenant_id'', true)) '
      '   WITH CHECK (tenant_id::text = current_setting(''app.current_tenant_id'', true))',
      t
    );
  END LOOP;
END $$;

-- Optional: HNSW index for embeddings (run after data exists; adjust lists/m as needed)
-- CREATE INDEX IF NOT EXISTS resource_chunks_embedding_hnsw
--   ON resource_chunks USING hnsw (embedding vector_cosine_ops);
