# Generated by Django 6.1 on 2026-09-06 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_dedupe_current_session_semester'),
        ('learning', '0004_plantemplate_is_public'),
        ('tenants', '0003_tenantrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('lecture', 'Lecture Timetable'), ('exam', 'Exam Timetable'), ('events', 'Events')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=512)),
                ('source_format', models.CharField(default='csv', max_length=16)),
                ('event_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('error_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('import_log', models.JSONField(blank=True, default=list)),
                ('committed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_schedules', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_schedules', to='academics.faculty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_schedules_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('lecture', 'Lecture'), ('exam', 'Exam'), ('study', 'Study Session'), ('office_hours', 'Office Hours'), ('institution', 'Institution Event'), ('reminder', 'Reminder')], default='reminder', max_length=20)),
                ('layer', models.CharField(choices=[('personal', 'Personal Study Plans'), ('academic', 'Academic Lectures'), ('exams', 'Exam Timetable'), ('office_hours', 'Office Hours'), ('institution', 'Institutional Events')], default='personal', max_length=20)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('course_code', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('tenant', 'Institution-wide')], default='private', max_length=20)),
                ('recur_rule', models.CharField(blank=True, default='', help_text='Optional RRULE-compatible recurrence string (e.g. WEEKLY;BYDAY=MO,WE).', max_length=255)),
                ('reminders_minutes', models.JSONField(blank=True, default=list, help_text='List of lead times in minutes before the event at which to send notifications.')),
                ('notify_enabled', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='academics.courseoffering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events_created', to=settings.AUTH_USER_MODEL)),
                ('office_hours', models.ForeignKey(blank=True, help_text='Parent event pointer if this is a recurring office-hour slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calendar.calendarevent')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='learning.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='For personal/private events; NULL for institution-wide events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['tenant', 'layer', 'start'], name='calendar_ev_tenant__14a9d9_idx'), models.Index(fields=['tenant', 'user', 'start'], name='calendar_ev_tenant__94a32f_idx'), models.Index(fields=['tenant', 'status'], name='calendar_ev_tenant__7dff96_idx'), models.Index(fields=['tenant', 'course_offering'], name='calendar_ev_tenant__68b840_idx'), models.Index(fields=['tenant', 'plan'], name='calendar_ev_tenant__a0661c_idx')],
            },
        ),
    ]
