# Generated by Django 6.1 on 2026-09-10 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_created_at_index_optin'),
        ('calendar', '0002_alter_calendarevent_tenant_and_more'),
        ('tenants', '0004_created_at_index_optin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calendarschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='calendarschedule',
            index=models.Index(fields=['created_at'], name='calendar_sc_created_008202_idx'),
        ),
    ]
