# Generated by Django 6.1 on 2026-09-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_concept_tenant_alter_conceptedge_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conceptedge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
