# Generated by Django 6.1 on 2026-08-30 14:56

from django.db import migrations, models


def forward_rename_admin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="admin").update(role="tenant_admin")


def reverse_rename_admin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="tenant_admin").update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_key_user_avatar_preset_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('tenant_admin', 'Tenant Admin')], default='student', max_length=20),
        ),
        migrations.RunPython(forward_rename_admin, reverse_rename_admin),
    ]
