# Generated by Django 6.1 on 2026-09-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_quiz_due_date'),
        ('resources', '0004_resourceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='source_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resources.resourcechunk'),
        ),
    ]
