# Generated by Django 6.1 on 2026-08-27 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_allowed_email_domains_tenant_branding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(db_index=True, max_length=254)),
                ('requester_role', models.CharField(blank=True, max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_slug', models.SlugField(blank=True, max_length=100)),
                ('institution_domain', models.CharField(blank=True, max_length=255)),
                ('institution_type', models.CharField(blank=True, choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college', 'College'), ('other', 'Other')], default='university', max_length=50)),
                ('estimated_students', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('provisioned_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to='tenants.tenant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tenant_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tenant_requ_status_e6fc99_idx')],
            },
        ),
    ]
