# Generated by Django 6.1 on 2026-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('formula', 'Formula'), ('system_event', 'System Event')], default='markdown', max_length=20),
        ),
    ]
