# Generated by Django 6.1 on 2026-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], help_text='Answer confidence based on retrieval quality.', max_length=10, null=True),
        ),
    ]
