# Generated by Django 6.1 on 2026-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_confidence_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Good'), (-1, 'Bad')], help_text='User feedback on answer quality (1 = good, -1 = bad).', null=True),
        ),
    ]
