# Generated by Django 6.1 on 2026-08-23 05:31

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('visibility_scope', models.CharField(choices=[('private', 'Private'), ('course', 'Course'), ('programme', 'Programme'), ('department', 'Department'), ('faculty', 'Faculty'), ('institution', 'Institution')], default='course', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('storage_key', models.CharField(blank=True, max_length=1024)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.courseoffering')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.faculty')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.programme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('permission', models.CharField(default='read', max_length=50)),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.courseoffering')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_permissions',
            },
        ),
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'db_table': 'resource_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ResourceChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('resource_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resources.resourceversion')),
            ],
            options={
                'db_table': 'resource_chunks',
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['tenant', 'processing_status'], name='resources_tenant__6a60f0_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['tenant', 'visibility_scope'], name='resources_tenant__b1257b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course_offering'], name='resources_course__f01dac_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceversion',
            constraint=models.UniqueConstraint(fields=('resource', 'version_number'), name='uniq_resource_version'),
        ),
        migrations.AddIndex(
            model_name='resourcechunk',
            index=models.Index(fields=['tenant', 'resource_version'], name='resource_ch_tenant__7ae677_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcechunk',
            constraint=models.UniqueConstraint(fields=('resource_version', 'chunk_index'), name='uniq_chunk_index'),
        ),
    ]
