# Generated by Django 6.1 on 2026-08-28 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_add_has_extractable_text'),
        ('tenants', '0003_tenantrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_summaries', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'db_table': 'resource_summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'resource', '-created_at'], name='resource_su_tenant__1c8d3a_idx')],
            },
        ),
    ]
