# Generated by Django 6.1 on 2026-09-17 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_protect_tenant_fk'),
        ('resources', '0007_protect_tenant_fk'),
        ('tenants', '0004_created_at_index_optin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('inaccurate', 'Inaccurate or misleading content'), ('copyright', 'Copyright infringement'), ('offensive', 'Offensive or inappropriate content'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resource_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='moderation_status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged pending review'), ('removed', 'Removed by moderator')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['tenant', 'moderation_status'], name='resources_tenant__bb043c_idx'),
        ),
        migrations.AddField(
            model_name='resourcereport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcereport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_resource_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcereport',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcereport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='resourcereport',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='resource_re_tenant__60e0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcereport',
            index=models.Index(fields=['tenant', 'resource', 'created_at'], name='resource_re_tenant__f8dde0_idx'),
        ),
    ]
